### ISSUE TITLE
My reflections

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109#41]
Based on peer feedback, The Titanic ship schematic with passenger cabin locations is a clean, easy to understand, and easy to use dashboard which helps users analyze and explore the proposed research question succinctly captured by the jumbotron title. The use of the dropdown as the single interactive feature in combination with the two static horizontal bar charts for survival rates by class and deck respectively is effective at showing how passenger fates vary by these two attributes which is difficult to visualize in two dimensions on a single plot since all three classes of passenger cabins (1-3) are found on all seven decks (A-G).

In its current form, the dashboard does not consider passenger fates by other attributes such as gender, age, marital status, or port of origin which are interesting but separate research questions requiring additional visualizations. To enhance the visualization of the current research question, we could also consider using colour to encode the three classes in the deck levels legend where the area of each colour is proportional to the share of its corresponding cabins class on each deck level. A more ambitious improvement would be to create a 3D interactive visualization of the ship which would allow the user to rotate the ship about the x, y and z axes to visualize passenger fate by specific cabin class, deck and nautical location (i.e. bow-stern, port-starboard) at a single glance with tooltips providing additional passenger attributes.

Process wise, I believe we have communicated effectively using Github Issues while our strict adherence to the git push and pull request protocol in combination with appropriate use of Slack notifications has allowed us to work remotely with high efficiency and without merge conflicts.

**Comment by RobBlumberg** [comment]
The research question we set out to answer was whether a passenger's cabin location on the Titanic had an effect on their chance of survival. Answering this question could ultimately help engineers design safer ships in the future, as they could avoid design implementations from the Titanic that may have led to high death rates.  The dashboard in its current state is effective at providing insight into this question, since the first visualization allows users to navigate different decks of the ship and see where passengers died or survived. Thus, a cruise line designer could focus in on "death clusters" and attempt to find out if there were sub-standard safety features in these areas of the ship which we would not want to replicate.  In addition to this, the "survival rate by deck level" plot helps indicate if some levels were lacking compared to other with regards to safety features. Similarly, the "survival rate by class" plot helps indicate if there were differences in terms of safety features between different class cabins.

Despite what is mentioned above, our dashboard had several important limitations which need to be considered, especially when trying to draw conclusion about our research question. First of all, our visualization assumes that some non-negligible proportion of all passengers were in their cabins at the time of the disaster.  Additionally, the lack of historical records with information about each passenger's cabin location means that we have only plotted a sample of the population of all passengers, and so we need to be careful about drawing conclusions for the whole population. Finally, we need to be careful about confusing correlation and causation. For example, class may affect the survival rate, not due to cabin safety, but due to the probable link between passenger class and societal status (meaning first class passengers were probably more likely to get on a safety boat). Nevertheless, the information provided could still lead to hypotheses about ship safety, which would subsequently be tested and confirmed as true or false.
