### ISSUE TITLE
milestone2 submission checklist

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109#61]
Now that we have successfully deployed to Heroku, here are the submission requirements for milestone2. I have extracted from milestone2.md and numbered these below:

**In the README.md file of your individual milestone2 homework repo on GitHub.ubc.ca, include:**  

1.  A link to team project repo on GitHub.com
2.  A link to your deployed app on Heroku (for e.g., https://{app-name}.herokuapp.com) 
     _This MUST match the version of the app of the submitted code Expectations_

**Overall App Deployment**  
 
3. When you finish your app, create a branch on GitHub.com called milestone2
4. Deploy your Dash app to heroku.com as described in Lecture 3 using the milestone2 branch. Name the app <GITHUB_REPO_NAME_milestone2>. Sometimes deployment will introduce bugs, so make sure to save some time for debugging!
5. In addition to your Dash app submission, you must document the functionality of your Dash app in the README.md file in your **team's GitHub.com public repo** for this milestone. 
6. Also include a link to your deployed app in the README.md file.

_Note: You should use proper grammar and full sentences in your README. Point form may occur, but should be less than 10% of your written documents._

**Comment by RobBlumberg** [comment]
I launched the app on heroku from my forked repo since I don't have access  to the main repo through heroku, but I saw a message on slack from Firas who said this was ok. So I think we can ignore points 3/4. 

Also, now that we've deployed the app, we can see that we can adjust the element positioning/dimensions by zooming, so I think we should add a note on the dashboard letting users know that they may need to adjust the zoom in their web browser to see the dashboard properly.

So I suggest the following:
- I can add a note in the dashboard about zooming, run the app on heroku through my cloned repo submit a PR with the small changes. These should be the last changes we make to the app, so i'll send you all the link to put in your milestone2 repo's. 
- Someone can take up the task of documenting the functionality of our app in the README, and at the same time, add the link to the deployed dashboard. 

Other than that I think we're done

**Comment by gptzjs** [comment]
OK sounds good. I will do this:

- Someone can take up the task of documenting the functionality of our app in the README, and at the same time, add the link to the deployed dashboard.

**Comment by RobBlumberg** [comment]
Great, I will post back in here when I've submitted the PR, and will have the link ready

**Comment by RobBlumberg** [comment]
Submitted the PR. Here is a link to the app on heroku: 

https://dsci-532-group-109-milestone2.herokuapp.com/

**Comment by gptzjs** [comment]
This task is completed and I will submit PR now

Someone can take up the task of documenting the functionality of our app in the README, and at the same time, add the link to the deployed dashboard.
