### ISSUE TITLE
Milestone 3 Discussion

### ISSUE THREAD

**Issue by gptzjs** [UBC-MDS/DSCI_532_GROUP_109#65]
Let's have a quick meeting after class today before lunch

I think we should be able to get everything done for milestone 3 in tomorrow's lab and if necessary we can stay after the lab to finish

**Comment by RobBlumberg** [comment]
I think we can get a lot done in the lab as well. I'm just going to make a high level to-do list so that we have an idea of what we need to address during the lab session:

- 1. Clean up code: my initial thoughts are to perform the wrangling in a jupyter notebook and then create data files which are imported into the plotting functions, rather than doing the wrangling in the plotting functions themselves. We should also ensure we are abiding by PEP-8 styling and document our functions (already done to some extent - but let's make sure this is done properly). 

- 2. File organization: for the most part, our repo is well organized, other than the fact that we had to put the data directory in the src directory, as well as in the root. We should get our code to run such that it doesn't depend on the data folder that is in the src directory.
- 3. Reproduce viz's in R and provide screenshot of progress
- 4. Update work contract: (I think this is likely not necessary unless we get more feedback from TA's)
- 5. Address peer feedback: we'll be able to tackle this point after tomorrow's in-lab activity

I can possibly get started on points 1 and 2 tonight (specifically starting the wrangling and exporting into data files). We can tackle points 3-5 when we work together tomorrow.

Let me know your thoughts on this

**Comment by gptzjs** [comment]
Good plan Rob, let us know if you need a hand for anything on 1 and 2

**Comment by gptzjs** [comment]
Closing this as all tasks completed in lab today
